- download artifact

diff --git a/.github/workflows/buildcd.yaml b/.github/workflows/buildcd.yaml
--- a/.github/workflows/buildcd.yaml
+++ b/.github/workflows/buildcd.yaml
@@ -29,3 +29,28 @@ jobs:
         uses: actions/upload-pages-artifact@v4
         with:
           path: _site
+
+  cd:
+    name: Continuous Deployment to Production
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Download site artifact
+        uses: actions/download-artifact@v6
+        with:
+          name: github-pages
+          path: .
+
+      - name: Extract pages artifact tar
+        run: |
+          set -e
+          echo "Looking for .tar file in root..."
+          TARFILE=$(find . -maxdepth 1 -type f -name "*.tar" -print -quit)
+          if [ -z "$TARFILE" ]; then
+            echo "ERROR: No tar archive found in root."
+            exit 1
+          else
+            echo "Found tar archive: $TARFILE"
+            mkdir -p _site
+            tar -xvf "$TARFILE" -C _site
+          fi
